### ISSUE TITLE
Misstatement of non-centered implementation?

### ISSUE THREAD

**Issue by eveskew** [betanalpha/knitr_case_studies#1]
Awesome resource Michael. However, I think there's a conflict between your description of the non-centered implementation of the Eight Schools model and the actual Stan code. The code states that "theta[j] = mu + tau * theta_tilde[j]" whereas the written description of the model has sigma in place of tau. Figured it would be worth the clarification for those (like myself) who are just getting familiar with coding non-centered versions of models.

**Comment by betanalpha** [comment]
Good catch — a fix has been pushed.  Thanks!
