### ISSUE TITLE
Minor comment on censoring vs truncation in "A Principled Bayesian Workflow"

### ISSUE THREAD

**Issue by to-mi** [betanalpha/knitr_case_studies#10]
Thanks for the great article on the Bayesian workflow. This is just a minor comment on the terminology of censoring and truncation in the given example case.

The text says:
"When the student repeated the measurement for detectors in this state they unintentionally induced a censored obsevation where the Poisson distribution for the observations is cutoff at a certain value."

But based on the terminology that I've learned from survival analysis, this would actually be truncation rather than censoring, since the observations that went over the scale of the sensor are not recorded at all in the data (they would be censored, if the student had recorded each case where the measurement went over the scale). This terminology seems also to follow the one in Bayesian Data Analysis book (2nd edition), Chapter 7.8.

(There's also a typo "obsevation" in the quoted sentence above.)

**Comment by betanalpha** [comment]
Resolved in 5325bf9daa01625bba1a105f2506fa18ef05b1c3.
