### ISSUE TITLE
Typo in probability theory doc: complement B1 should be in set of Reals

### ISSUE THREAD

**Issue by ssp3nc3r** [betanalpha/knitr_case_studies#13]
Hi Michael, thanks for writing up all the tutorials. I wasn't sure how you'd like feedback/typo catching, so I'll just post here. In the doc probability theory, the complement of B1 should be in the set of Reals.

Best,
Scott

**Comment by betanalpha** [comment]
Thanks!  Fixed in an upcoming update.
