### ISSUE TITLE
Possible typo in "Identifying Bayesian Mixture models"

### ISSUE THREAD

**Issue by connor-duffin** [betanalpha/knitr_case_studies#15]
Hi Michael,

Thanks for these write-ups; they are fantastic. In "Identifying Bayesian Mixture Models" I think the sum in the first equation of section 4 should be a product, to properly define the likelihood.

Best,
Connor

**Comment by betanalpha** [comment]
Thanks, you are correct.  This typo has been on my to-fix list for a while now but there have just been other case study priorities.
