### ISSUE TITLE
Half Normal or Log Normal

### ISSUE THREAD

**Issue by apeterson91** [betanalpha/knitr_case_studies#2]
Your gaussian processes 3 write-up states that the priors for the hyper parameters are half normal,

e.g. 
$$\alpha \sim $ half- $\mathcal{N}(0,2)$$

and the corresponding code is
`
parameters{
 ...
real<lower=0> alpha;
}
model{
alpha ~ normal(0,2);
...
}
`

But according to the stan reference manual (v 2.16.0) pg. 400: "If a variable X is declared to have a lower bound $a$,  it is transformed to be an unbounded random variable $Y$, where ." 

$$ Y = log (X - A)$$

which in this case would just be the log, suggesting that the new random variable is log normal, not half - would you mind clearing up this discrepancy for me? 

I'm using a similar parameterization in a model I'm working with and would like to know the "real" prior distribution I'm using. - Many Thanks.

**Comment by betanalpha** [comment]
Stan automatically adds the Jacobian to ensure that we are indeed specifying a half normal distribution and not a log normal distribution.  Please consult the Stan manual for more information.
