### ISSUE TITLE
expression for prior_sd_lambda on inverse gamma is not quite correct

### ISSUE THREAD

**Issue by arabidopsis** [betanalpha/knitr_case_studies#20]
There are 2 places in `principled_bayesian_workflow.Rmd` where the expression
for the sd of an inverse gamma is used viz:
```R
prior_sd_lambda <- sqrt( (9.21604)**2 / ((3.48681 - 1)**2 * (3.48681 - 1)) )
 ```
I think this should be (note the -2):
```R
prior_sd_lambda <- sqrt( (9.21604)**2 / ((3.48681 - 1)**2 * (3.48681 - 2)) )
````
BTW: awesome work!

**Comment by betanalpha** [comment]
Thanks!  There are numerous small errors, including the prior specifications and the prior standard deviations beyond the first iteration.  I will be updating everything here, along with the addition of new material, once I finish a few more new case studies.  I will be sure to rectify this along with everything else.
