### ISSUE TITLE
Syntax Error in `principled_bayesian_workflow/sample_joint_ensemble4.stan`

### ISSUE THREAD

**Issue by lsandig** [betanalpha/knitr_case_studies#21]
I just tried to compile the principled bayesian workflow case study, but this fails with a stan syntax error. 
In `sample_joint_ensemble4.stan` you declare an array `y[N]` but try to assing to `y_ppc[n]` in the loop. Changig `y_ppc` to `y` would be consistent with the other `sample*.stan` files.

**Comment by betanalpha** [comment]
Thanks! This is already fixed in a local version of the code which will be pushed once I get a chance to update the case study.  I'm going to close the issue for the time being.
