### ISSUE TITLE
Prior standard deviation in "A Principled Bayesian Workflow"

### ISSUE THREAD

**Issue by dipetkov** [betanalpha/knitr_case_studies#22]
Since the prior is a half-normal (i.e., truncated at 0), shouldn't we use `qnorm(0.995)` instead of `qnorm(0.99)` to get the prior standard deviation?
``` r
TruncatedNormal::qtnorm(0.99, 0, 15 / qnorm(.995), 0, Inf)
#> [1] 15
TruncatedNormal::qtnorm(0.99, 0, 15 / qnorm(.99), 0, Inf)
#> [1] 16.60863

# where

15 / qnorm(.995)
#> [1] 5.823367
15 / qnorm(.99)
#> [1] 6.447875
```

<sup>Created on 2019-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by betanalpha** [comment]
Thanks!  This is correct and has been fixed in local edits (along with many other bugs and types) that will eventually make it to the published version when I get a chance at a proper update.  For now I'm going to close this.
