### ISSUE TITLE
Typo in Metropolis-Hastings conditional PDF

### ISSUE THREAD

**Issue by siddhantwahal** [betanalpha/knitr_case_studies#27]
Hi!

I think the Metropolis-Hastings conditional PDF in `markov_chain_monte_carlo.Rmd` should be:

```
$$
T(q' \mid q) = a(q', q) \cdot Q (q' \mid q )
+ \left(1 - \int a(q, q') Q(q' \mid q) d q' \right) \cdot \delta(q - q').
$$
```

instead of 
```

$$
T(q' \mid q) = a(q', q) \cdot Q (q' \mid q )
+ \left(1 - a(q, q') \right) \cdot \delta(q - q').
$$
```

Else, the conditional PDF T(q' | q) doesn't integrate to 1. See, for instance, pg 3 of this [note](https://ocw.mit.edu/courses/economics/14-384-time-series-analysis-fall-2013/lecture-notes/MIT14_384F13_lec25.pdf).

Great work by the way! I found the bit on correctly estimating the maximum lag for the autocorrelation very useful.

**Comment by betanalpha** [comment]
Yes, thanks!  I always forget the integral on rejection probability unless I’m
working out the derivation in full.  I’ll include a correction when I get to updating 
the case study next.
