### ISSUE TITLE
Typo in 'Underdetermined linear regression'?

### ISSUE THREAD

**Issue by fweber144** [betanalpha/knitr_case_studies#32]
I am not sure if I got everything from the 'Underdetermined linear regression' case study correctly, but line 50 of [linear_regression_w_proj.stan](https://github.com/betanalpha/knitr_case_studies/blob/master/underdetermined_linear_regression/linear_regression_w_proj.stan) is
```
gamma_par = append_row(beta, alpha) - gamma_perp;
```
though I would have thought it should be
```
gamma_par = (append_row(beta, alpha) - R) - gamma_perp;
```
Am I getting something wrong or is this a typo?

**Comment by betanalpha** [comment]
No, you are correct -- because I never use `gamma_par` anywhere I didn't catch the offset.  Thanks!
