### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JeremySilver** [betanalpha/knitr_case_studies#35]
I noticed what may be a minor typo in your excellent Gaussian Processes tutorial. I believe that line 1342 (at commit 8db2461) of `knitr_case_studies/gaussian_processes/gaussian_processes.Rmd` should be
`                  N_obs=data$N_obs, x_obs=data$x_obs, y_obs=data$y_obs,`
currently it is
`                  N_obs=data$N_obs, x=data$x_obs, y_obs=data$y_obs,`

**Comment by betanalpha** [comment]
You're right, thanks.  Now wondering how the markdown even compiled!  

I'll fix this when I get around to updating the case study.

**Comment by betanalpha** [comment]
Resolved in e10083abbcdb65c745f840ab9d2da58229fa9af3.
