### ISSUE TITLE
Potential Bayes' Theorem typo in Probability Theory on Product Spaces

### ISSUE THREAD

**Issue by roualdes** [betanalpha/knitr_case_studies#36]
Would you mind taking a minute to look at the last two equations of [subsection 3.4 in Probability Theory on Product Spaces](https://betanalpha.github.io/assets/case_studies/probability_on_product_spaces.html#34_from_decomposition_to_conditioning)?  There are two issues that I'm struggling to wrap my head around.

1. I'm used to seeing Bayes' Theorem flip the conditioning in the numerator of the right hand side,

P(A | B) = P(B|A) P(A) / P(B),

but it appears that you have the same conditioning happening on the left hand side as on the right hand side.

\pi(x_2 | \tilde{x}_1) = \frac{ \pi(x_2 | \tilde{x}_1) }{ constant } \pi(x_2)

Given Section 1.3, it seems that \pi(\tilde{x}_1 | x_2) should rightfully be function defined on x_1 \cross X_2.  Is this interpretation correct?

2. The constant in the denominator of these equations is different, when I don't think it should be.  In the first, you integrate with respect to x1, dx1, and in the second, x2, dx2. They should both integrate over x2, right?

Thanks for these great case studies.  I really appreciate the clarity of mathematical concepts that you offer, especially when it comes to random variables.

**Comment by betanalpha** [comment]
Yes, thank you so much!  You are correct that these are unfortunately typos on my end!  I've noted the problem and will fix them when I next have a chance of updating this case study.

**Comment by betanalpha** [comment]
Fixed in dfb96237152414a4c8c1a5d6c8639da9915c2378.  Thanks!
