### ISSUE TITLE
Typo in posterior z-score?

### ISSUE THREAD

**Issue by fweber144** [betanalpha/knitr_case_studies#38]
In the case study "Towards A Principled Bayesian Workflow", I think there's a typo in the definition of the posterior z-score (section 1.3.2 "A Bayesian Eye Chart"): Shouldn't the denominator be the marginal posterior standard deviation instead of the marginal posterior mean (see also [here](https://betanalpha.github.io/assets/case_studies/modeling_and_inference.html#332_calibration_posterior_behaviors))?

**Comment by betanalpha** [comment]
Correct, thanks for pointing this out. This is already on the overdue to-fix list!

**Comment by betanalpha** [comment]
aeab31509b8e37ff05b0828f87a3018b1799b401
