### ISSUE TITLE
Typo in interpretation of posterior z-score and contraction?

### ISSUE THREAD

**Issue by fweber144** [betanalpha/knitr_case_studies#39]
In the case study "Towards A Principled Bayesian Workflow", I think the sentence

> On the other hand a posterior distribution with both a small posterior z-score and a small posterior contraction indicates ideal learning behavior.

has to read

"On the other hand a posterior distribution with both a small posterior z-score and a high posterior contraction indicates ideal learning behavior."

Otherwise, it would also contradict with the sentence

> Likewise a posterior distribution with a small posterior z-score and a small posterior contraction is only poorly informed by the observations.

**Comment by betanalpha** [comment]
Correct, thanks for pointing this out.  This is already on the overdue to-fix list!

**Comment by betanalpha** [comment]
Addressed in aeab31509b8e37ff05b0828f87a3018b1799b401.
