### ISSUE TITLE
Probability distribution breakdown in figure error?

### ISSUE THREAD

**Issue by xcurry** [betanalpha/knitr_case_studies#4]
The figures show:

P(A_5)+P(A_6) = P (A_1) = 1

(and similarly the one next to it). That does not look correct as P(A_1) + P (A_2) = P(A_0) = 1. It should be:

P(A_5) + P(A_6) = P(A_1) (but not equal to 1).

**Comment by betanalpha** [comment]
Fixed in upcoming draft.  Thanks.
