### ISSUE TITLE
Typos in figures of section 4.3.4 of probability on product spaces?

### ISSUE THREAD

**Issue by prashjet** [betanalpha/knitr_case_studies#40]
Hi there - I think I've spotted some typos in [Section 4.3.4 of probability on product spaces](https://betanalpha.github.io/assets/case_studies/probability_on_product_spaces.html#434_directed_graphical_models_for_conditional_distributions), specifically in the equations in the figures:
1. in the first figure - i.e.`dgm_condition_1.png` - the first line should be condtional on \tilde{x}_1 rather than \tilde{x}_4
2. in the second figure - i.e.`dgm_condition_2.png` - on the last line, in the final two factors, x_4 should be replaced by x_1

Also: thanks for all the great resources!

**Comment by betanalpha** [comment]
Fixed in dfb96237152414a4c8c1a5d6c8639da9915c2378.  Thanks!
