### ISSUE TITLE
Ordinal Regression: Wrong indices in figure multi.tex

### ISSUE THREAD

**Issue by FlorianPargent** [betanalpha/knitr_case_studies#49]
Thank you for all your excellent case studies!

In the right plot of figure multi.tex in the Ordinal Regression case study, some of the cut point indices are wrong.
I think it should be:
$p_{4} = \Pi(c_{4}) - \Pi(c_{3})$
$\Pi(c_{4}) = 1$
$\Pi(c_{3})$
$\Pi(c_{2})$
$\Pi(c_{1})$
$\Pi(c_{0}) = 0$

**Comment by betanalpha** [comment]
Thanks -- I really butchered that when I changed index conventions!  I've updated the figure and the online case study.
